name: CI-CD Pipeline

on:
  push:
    branches: [ "main","test","test-2" ]
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # -----------------------------------------
  # CI: Testler
  # -----------------------------------------
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Account Testlerini çalıştır
        run: python manage.py test accounts

      - name: Dean Testlerini çalıştır
        run: python manage.py test dean

      - name: Hod Testlerini çalıştır
        run: python manage.py test hod

      - name: Students Testlerini çalıştır
        run: python manage.py test students